[package]
name = "bt-accounting"
version.workspace = true
edition.workspace = true

[dependencies]
bt-core = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
chrono-tz = { workspace = true }
proptest = { workspace = true }
